// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class UNIBDtestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void uNIBDtest() {
    driver.Navigate().GoToUrl("http://localhost:51818/");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) > a")).Click();
    driver.FindElement(By.Id("fnlnmn")).Click();
    driver.FindElement(By.Id("fnlnmn")).SendKeys("ГрГУ");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("+375294456784");
    driver.FindElement(By.Id("price-usd")).Click();
    driver.FindElement(By.Id("price-usd")).SendKeys("275");
    driver.FindElement(By.Id("price-byn")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) > a")).Click();
  }
}
